apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: sinusbot
  name: sinusbot
spec:
  ports:
  - name: "8087"
    port: 8087
    targetPort: 8087
  selector:
    io.kompose.service: sinusbot
status:
  loadBalancer: {}
