apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
  labels:
    io.kompose.service: sinusbot-1
  name: sinusbot-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

