apiVersion: v1
kind: PersistentVolume
metadata:
  name: sinusbot-claim0
  labels:
    io.kompose.service: sinusbot-claim0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes/teamspeakbot"